### ISSUE TITLE
DNS_ZONE_NAME not being picked up from config.json

### ISSUE THREAD

**Issue by dfoleypivotal** [cf-platform-eng/gcp-pcf-quickstart#62]
When I run deploy_pcf.sh it is failing saying that DNS_ZONE_NAME required. This value should be set based on the default / config.json. I was able to get the deployment to work by setting DNS_ZONE_NAME manually (export DNS_ZONE_NAME=pcf-zone)

running step: acceptEulas
accepted EULAs for 6 products
enabling Google Cloud APIs
waiting for 25 service enable operation(s) to complete
waiting for 3 service enable operation(s) to complete
waiting for 1 service enable operation(s) to complete
enusred 25 API(s) are enabled
validating Google Cloud Compute Engine quotas
Compute Engine quota is adequate, satisfied 21 rules
DNS_ZONE_NAME required

**Comment by mattysweeps** [comment]
@dfoleypivotal 

I believe this is an issue because I updated the Go variable names to uppercase acronyms (a style improvement). This trickled down into the reading of the `config.json` config file. Now, reading an old config file is incompatible with master branch because certain fields have different keys.

Try updating the keys of your config to match this:
```
cat env/pcf/config.json 
{
  "DNSZoneName": "pcf-zone",
  "ProjectID": "my-project",
  "BaseImageURL": "https://storage.cloud.google.com/ops-manager-us/pcf-gcp-2.3-build.194.tar.gz",
  "EnvName": "pcf",
  "Region": "us-east1",
  "PivnetAPIToken": "mytoken",
  "Zone1": "us-east1-b",
  "Zone2": "us-east1-c",
  "Zone3": "us-east1-d",
  "SmallFootprint": true,
  "IncludeHealthwatch": false
}
```
Notice the `DNSZoneName`. I bet your config has `DnsZoneName`.

**Comment by mattysweeps** [comment]
@dfoleypivotal there's more to it than that. There is a bug in the `source-config` command which is how the environment variables get set. I'm working on a fix now
